import { Article, Company } from "@/types";

export const sampleArticles: Article[] = [
  {
    id: "1",
    title: "大和ハウス工業、2025年度の住宅受注が前年比15%増加",
    summary:
      "大和ハウス工業は2025年度の住宅事業における受注高が前年比15%増加したと発表。戸建住宅のxevoシリーズが好調で、ZEH対応住宅の需要増加が牽引した。",
    content: null,
    source_url: "https://example.com/1",
    source_name: "住宅産業新聞",
    thumbnail_url: null,
    category: "企業動向",
    article_type: "企業",
    status: "published",
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "国土交通省、2025年の新設住宅着工戸数を発表 — 前年比3.2%減",
    summary:
      "国土交通省が発表した2025年の新設住宅着工戸数は約78万戸で、前年比3.2%の減少となった。金利上昇と建材価格の高止まりが影響。",
    content: null,
    source_url: "https://example.com/2",
    source_name: "国土交通省",
    thumbnail_url: null,
    category: "統計データ",
    article_type: "業界",
    status: "published",
    published_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "3",
    title: "積水ハウス、次世代スマートホーム「Platform House」を全国展開",
    summary:
      "積水ハウスは、AIとIoT技術を融合した次世代スマートホーム「Platform House」の全国展開を開始。健康管理やエネルギー最適化機能を標準搭載。",
    content: null,
    source_url: "https://example.com/3",
    source_name: "新建ハウジング",
    thumbnail_url: null,
    category: "技術・トレンド",
    article_type: "企業",
    status: "published",
    published_at: new Date(Date.now() - 172800000).toISOString(),
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "4",
    title: "住宅ローン金利、主要銀行が0.15%引き上げを発表",
    summary:
      "三菱UFJ銀行、三井住友銀行など主要行が住宅ローンの固定金利を0.15%引き上げると発表。日銀の金融政策正常化を受けた動き。",
    content: null,
    source_url: "https://example.com/4",
    source_name: "日本経済新聞",
    thumbnail_url: null,
    category: "市場動向",
    article_type: "業界",
    status: "published",
    published_at: new Date(Date.now() - 259200000).toISOString(),
    created_at: new Date(Date.now() - 259200000).toISOString(),
    updated_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "5",
    title: "一条工務店、断熱性能で業界最高水準のUA値0.20を実現",
    summary:
      "一条工務店は新商品「グラン・スマート」で、UA値0.20という業界最高水準の断熱性能を実現。独自の外内ダブル断熱構法により、光熱費の大幅削減を可能に。",
    content: null,
    source_url: "https://example.com/5",
    source_name: "新建ハウジング",
    thumbnail_url: null,
    category: "技術・トレンド",
    article_type: "企業",
    status: "published",
    published_at: new Date(Date.now() - 345600000).toISOString(),
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "6",
    title: "省エネ基準適合義務化、2025年4月から全新築住宅に適用",
    summary:
      "改正建築物省エネ法により、2025年4月から全ての新築住宅に省エネ基準への適合が義務化される。ハウスメーカー各社は対応済みだが、中小工務店への影響が注目される。",
    content: null,
    source_url: "https://example.com/6",
    source_name: "住宅産業新聞",
    thumbnail_url: null,
    category: "政策・法規制",
    article_type: "業界",
    status: "published",
    published_at: new Date(Date.now() - 432000000).toISOString(),
    created_at: new Date(Date.now() - 432000000).toISOString(),
    updated_at: new Date(Date.now() - 432000000).toISOString(),
  },
];

export const sampleCompanies: Company[] = [
  {
    id: "1",
    name: "大和ハウス工業",
    short_name: "大和ハウス",
    slug: "daiwa-house",
    logo_url: null,
    description:
      "日本最大の住宅メーカー。戸建住宅、賃貸住宅、マンション、商業施設など幅広い事業を展開。",
    website: "https://www.daiwahouse.co.jp/",
    stock_code: "1925",
    tier: "大手",
    founded_year: 1955,
    headquarters: "大阪府大阪市",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "積水ハウス",
    short_name: "積水ハウス",
    slug: "sekisui-house",
    logo_url: null,
    description:
      "累計建築戸数世界一のハウスメーカー。鉄骨造・木造の戸建住宅、賃貸住宅を展開。",
    website: "https://www.sekisuihouse.co.jp/",
    stock_code: "1928",
    tier: "大手",
    founded_year: 1960,
    headquarters: "大阪府大阪市",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "一条工務店",
    short_name: "一条工務店",
    slug: "ichijo",
    logo_url: null,
    description:
      "断熱性能業界No.1のハウスメーカー。「家は、性能。」をコンセプトに高性能住宅を提供。",
    website: "https://www.ichijo.co.jp/",
    stock_code: null,
    tier: "大手",
    founded_year: 1978,
    headquarters: "東京都江東区",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "住友林業",
    short_name: "住友林業",
    slug: "sumitomo-forestry",
    logo_url: null,
    description:
      "木造住宅のリーディングカンパニー。BF構法による自由設計の木造住宅を展開。",
    website: "https://sfc.jp/",
    stock_code: "1911",
    tier: "大手",
    founded_year: 1691,
    headquarters: "東京都千代田区",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "積水化学工業",
    short_name: "積水化学",
    slug: "sekisui-chemical",
    logo_url: null,
    description:
      "セキスイハイムブランドで知られる。ユニット工法による高品質住宅を提供。",
    website: "https://www.sekisui.co.jp/",
    stock_code: "4204",
    tier: "大手",
    founded_year: 1947,
    headquarters: "大阪府大阪市",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "三井ホーム",
    short_name: "三井ホーム",
    slug: "mitsui-home",
    logo_url: null,
    description:
      "デザイン性の高いツーバイフォー工法の住宅メーカー。三井不動産グループ。",
    website: "https://www.mitsuihome.co.jp/",
    stock_code: null,
    tier: "大手",
    founded_year: 1974,
    headquarters: "東京都新宿区",
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "オープンハウス",
    short_name: "オープンハウス",
    slug: "open-house",
    logo_url: null,
    description: "都心部の戸建住宅に強み。急成長中の不動産・住宅企業。",
    website: "https://oh.openhouse-group.com/",
    stock_code: "3288",
    tier: "大手",
    founded_year: 1997,
    headquarters: "東京都千代田区",
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "旭化成ホームズ",
    short_name: "ヘーベルハウス",
    slug: "hebel-haus",
    logo_url: null,
    description:
      "ALCコンクリート「ヘーベル」を使用した鉄骨住宅。耐火・耐久性に優れる。",
    website: "https://www.asahi-kasei.co.jp/hebel/",
    stock_code: "3407",
    tier: "大手",
    founded_year: 1972,
    headquarters: "東京都千代田区",
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    name: "パナソニックホームズ",
    short_name: "パナソニックホームズ",
    slug: "panasonic-homes",
    logo_url: null,
    description:
      "パナソニックグループの住宅メーカー。IoT住宅やスマートシティ開発に注力。",
    website: "https://homes.panasonic.com/",
    stock_code: null,
    tier: "大手",
    founded_year: 1963,
    headquarters: "大阪府豊中市",
    created_at: new Date().toISOString(),
  },
  {
    id: "10",
    name: "タマホーム",
    short_name: "タマホーム",
    slug: "tama-home",
    logo_url: null,
    description:
      "低価格帯の注文住宅を提供。「品質も、価格も、叶う家。」をコンセプトに全国展開。",
    website: "https://www.tamahome.jp/",
    stock_code: "1419",
    tier: "中堅",
    founded_year: 1998,
    headquarters: "東京都港区",
    created_at: new Date().toISOString(),
  },
  {
    id: "11",
    name: "ミサワホーム",
    short_name: "ミサワホーム",
    slug: "misawa-home",
    logo_url: null,
    description:
      "蔵のある家で知られるハウスメーカー。木質パネル接着工法を採用。",
    website: "https://www.misawa.co.jp/",
    stock_code: null,
    tier: "大手",
    founded_year: 1967,
    headquarters: "東京都新宿区",
    created_at: new Date().toISOString(),
  },
  {
    id: "12",
    name: "トヨタホーム",
    short_name: "トヨタホーム",
    slug: "toyota-home",
    logo_url: null,
    description:
      "トヨタグループの住宅メーカー。自動車製造技術を活かした鉄骨ユニット工法。",
    website: "https://www.toyotahome.co.jp/",
    stock_code: null,
    tier: "大手",
    founded_year: 2003,
    headquarters: "愛知県名古屋市",
    created_at: new Date().toISOString(),
  },
];

export const sampleDraftArticles: Article[] = [
  {
    id: "draft-1",
    title: "ヘーベルハウス、新型制震装置を全商品に標準搭載へ",
    summary:
      "旭化成ホームズは、独自開発の新型制震装置「ハイパーフレーム」を2026年度から全商品に標準搭載すると発表。",
    content:
      "旭化成ホームズは、独自開発の新型制震装置「ハイパーフレーム」を2026年度から全商品に標準搭載すると発表した。従来の制震装置と比較して、地震エネルギーの吸収率が約40%向上。大規模地震時の建物変形を大幅に抑制できるという。",
    source_url: "https://example.com/draft-1",
    source_name: "新建ハウジング",
    thumbnail_url: null,
    category: "技術・トレンド",
    article_type: "企業",
    status: "draft",
    published_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "draft-2",
    title: "2026年度住宅エコポイント制度の概要が判明",
    summary:
      "国土交通省が検討中の2026年度住宅エコポイント制度の概要が明らかに。ZEH基準を満たす新築住宅に最大100万ポイントを付与。",
    content:
      "国土交通省が検討中の2026年度住宅エコポイント制度の概要が明らかになった。ZEH基準を満たす新築住宅に最大100万ポイント、省エネリフォームにも最大60万ポイントを付与する方針。予算規模は約1,500億円を見込む。",
    source_url: "https://example.com/draft-2",
    source_name: "住宅産業新聞",
    thumbnail_url: null,
    category: "政策・法規制",
    article_type: "業界",
    status: "draft",
    published_at: null,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "draft-3",
    title: "住友林業、木造超高層ビル「W350計画」の進捗を発表",
    summary:
      "住友林業は、2041年完成を目指す木造超高層ビル「W350計画」の最新進捗を発表。要素技術の開発が順調に進んでいるという。",
    content:
      "住友林業は、創業350周年にあたる2041年の完成を目指す木造超高層ビル「W350計画」の最新進捗を発表した。高さ350メートル、地上70階建ての木造超高層建築を実現するための要素技術の開発が順調に進んでいるという。",
    source_url: "https://example.com/draft-3",
    source_name: "日経クロステック",
    thumbnail_url: null,
    category: "企業動向",
    article_type: "企業",
    status: "draft",
    published_at: null,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
];
